apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
spec:
  completions: null
  parallelism: 2
  template:
    metadata:
      name: job-wq-1
    spec:
      containers:
      - name: jellyqueuereceiver
        image: avish1990/jelly-receive:1.0
      restartPolicy: OnFailure
